---
title: "Consejos prácticos para leer y escribir"
author: "Irvin Rojas"
institute: "CIDE"
date: "15 de septiembre"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")

library(tidyverse)
library(pacman)
library(janitor)
library(sandwich)
#library(nnet)
#library(mlogit)
library(readr)
library(clubSandwich)
library(modelsummary)
library(estimatr)

p_load(tidyverse, foreign, reshape2, psych, qwraps2, forcats, readxl, 
       broom, lmtest, margins, plm, rdrobust, multiwayvcov,
       wesanderson, sandwich, stargazer,
       readstata13, pscore, optmatch, kdensity, MatchIt, bootstrap, matlib, dplyr)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{css, echo = FALSE}
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}
```

.title[
# Sesión 9. Consejos prácticos para leer y escribir
]
.subtitle[
## Evaluación de Programas Sociales
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda

- En esta primera parte del curso hemos estudiado el diseño, implementación y análisis de experimentos

- Hemos visto ejemplos de estudios de intervenciones con diseños experimentales de muy diversa índole

  - Experimentos de campo
  - Estudios de correspondencia
  - RCTs a pequeña y gran escala

- Hemos enfatizado el diseño y cómo su integridad permite identificar efectos de tratamiento

- Hemos usado econometría para cuantificar dichos efectos

--

- Este es un breve resumen de las lecciones prácticas que quisiera que tuvieran en cuenta cuando estudien e implementen evaluaciones

- Muchos de estos principios 


---

class: inverse, middle, center

# Resumen de consejos prácticos

---

# Cuando leemos sobre el diseño

- Identificar la pregunta causal que se busca responder: ¿qué causa qué?

- Identificar los mecanismos por medio de los cuales esto podría ser cierto: recurrimos a la teoría económica

- Identificar cuáles son las característiacs del programa o intervención que se estudia

- Caracterizar el diseño de la evaluación
  - ¿Cómo se asignó el tratamiento? ¿Hubo una o varias etapas de aleatorización?
  - ¿Quiénes recibieron los beneficios de la intervención o programa?
  - ¿Existieron requisitos de elegibilidad?
  - ¿Todos los asignados a recibir la intervención efectivamente la recibieron?

- Caracterizar las posibles amenazas a la integridad del diseño


---

# Cuando leemos sobre el diseño

- Buscar evidencia de la integridad del diseño

  - ¿Los grupos de tratamiento y control tienen características similares antes de la intervención?
  - ¿Qué tan grande es la atrición? ¿La atrición es diferenciada entre los grupos de tratamiento y control?
  
- Darle uso a las tablas de estadística descriptiva

  - La media y la desviación estándar de $y$ nos serán informativos para interpretar los resultados
  - ¿Tienen sentido los mínimos y máximos de las variables que se nos presentan?
  
- Identificar la especificación económetrica que da lugar a los resultados principales
  - Nivel de agregación
  - Controles
  - Tipo de errores
  
---

# Cuando interpretamos tablas de resultados

- ¿Cuál es la variable dependiente?

- ¿Cuál es la variable independiente clave? ¿Cuáles son los controles?

- ¿Qué regresores no están reportados, pero sí fueron incluidos en el análisis

- Si se tienen más de una variable dependiente, ¿cómo se relacionan dichas variables?

- ¿Se toma en consideración el problema de probar múltiples hipótesis?

- ¿Qué significan los símbolos y caracteres empleados?
  
  - Estrellas de significancia
  - Paréntesis y corchetes
  
---

# Sobre los análisis secundarios

- ¿Qué evidencia adicional se presenta y cómo abona a nuestro entendimiento de la relación causal?

  - Efectos diferenciados entre grupos (por ejemplo, entre hombres y mujeres, entre hogares rurales y urbanos, entre hogares pobres y ricos, entre otros)
  
  - Pruebas de poder: ¿el diseño planteado tiene el poder estadístico para detectar efectos de cierto tamaño?
  
  - Análisis costo beneficio
  
  - Efectos de *derramamiento*
  
  - Efectos placebo: ¿si realizo el análisis sobre variables donde yo no esperaría ver efectos, efectivamente obtengo un cero?

---

# Sobre el balance

- En la [Tarea 1](https://rojasirvin.github.io/EPS2020/tareas/tarea1.html)  tuvimos un ejemplo estilizado donde las cosas salieron mal y toda la evidencia apuntaba en esa dirección

  - Observables diferentes entre tratados y no tratados
  - Observables predicen el estado de tratamiento
  
- En la práctica, puede que nos encontremos en algún área gris

--
 
- Una posibilidad es encontrar que *algunas* de las características no están balanceadas y los observables tienen algo de poder predicitvo para el estado de tratamiento

  - Discutir cuáles son las características que no están balanceadas y la significancia económica de los desbalances
  - Incluir el conjunto completo de características usadas para mostrar el balance como covariables en las regresiones de efecto de tratamiento
  - Explicar las posibles razones por las cuales estos desbalances ocurren
  - Recordemos que algunos desbalances pueden ocurrir por suerte


---

# Sobre el balance

- Un estudio comprometido tendrá algunas de las siguientes características

  - Existen diferencias económica y estadísticamente significativas en características observadas entre tratados y no tratados antes de la intervención
  
  - Existen diferencias económica y estadísticamente significativas en las variables de resultados observadas entre tratados y no tratados antes de la intervención
  
  - Tendrá un alta tasa de atrición diferenciada entre grupos de tratamiento y control
  
  - Si el estudio tiene incumplimiento imperfecto, poco o nada se discute sobre las diferencias en la adopción

---

# Conceptos que deben tener a la mano siempre

- Planteamiento de pruebas de hipótesis: ¿cuál es la $H_0$ que se desea probar?

- Relación entre los estadísticos de prueba (como $t$ o $F$), su valor $p$ y la hipótesis nula

  - A veces los estudios nos presentan $t$ y otros $p$, pero debemos recordar que son dos caras de la misma moneda y debemos tener la capacidad de ligarlos a la interpretación de resultados

- Relación entre los errores estándar y los estadísticos (por ejemplo, el $t$) en una regresión

- Cómo interpretar los coeficientes de efecto del tratamiento y de las *estrellas de significancia*

- Cuando anaizamos un estudio con LATE

  - ¿Cuál es la relación estructural, cuál es el coeficiente de interés y cómo se interpreta?
  - ¿Cuál es la primera etapa, cuál es el coeficiente de interés y cómo se interpreta?
  - ¿Cuál es la forma reducida, cuál es el coeficiente de interés y cómo se interpreta?

---

# Cuando escribimos sobre una intervención

- Dar contexto sobre el lugar y momento en que se realiza la intervención

- Dar contexto sobre el programa público o describir la intervención con detalle
  
- Ayudar al lector a entender la implementación del estudio por todos los medios

  - Incluir mapas de los lugares donde el estudio tuvo lugar
  - Una línea temporal es un buena ayuda visual para comprender la estructura de la intervención a lo largo del tiempo
  - Mostrar los cuestionarios empleados (el apéndice es un buen lugar para esto)

- Proveer la intuición económica de la relación causal estudiada: ¿por qué esperamos que $T_i$ afecte $y_i$

  - Varios de los artículos de evaluación mejor publicados incluyan un modelo microeconómico sólido para sustentar la intervención implementada
  - Aunque a veces no viable tener un modelo en el estudio, sí vale la pena al menos argumentar sobre la relación económica entre las variables estudiadas



---

# Cosas que evitar al escribir

- Una postura muy personal es evitar pies de página en exceso, aunque esto cambia entre asesores y coautores

- Eviten el uso incorrecto de mayúsculas y recuerden que las reglas ortográficas son distintas entre el español y otros idiomas

- Describir algunas de las dificultades de la implementación y el análisis, pero ser cuidadoso
  
  - No es de interés del lector si sus regresiones tardaron mucho en correr
  - No es relevante si su base de datos era muy grande o si tuvieron que trabajar mucho en limpiarla
  - Tampoco es relevante qué tan difícil fue el trabajo de campo, a menos de que esto tenga un impacto en la integridad del diseño<sup>1</sup>
  
.footnote[
[1] Al autor de este resumen le dio [chikungunya](https://www.who.int/es/news-room/fact-sheets/detail/chikungunya) mientras realizaba trabajo de campo en Oaxaca. Un blog o unas diapositivas de curso son un buen lugar para esa anéctoda
]


---

# Cuando reportamos resultados en tablas

- Mi sugerencia es reportar resultados de regresión en el siguiente formato

  - $\beta$ con estrellas de significancia para $\alpha$ de 10, 5 y 1%
  - Debajo de $\beta$, reportar los errores estándar entre paréntesis (reservar corchetes para otra nomenclatura)
  - En los pies de la tabla, aclarar la estructura de los errores (robustos, agrupados, bootstrap o lo que aplique) y la especificación econométrica usada para generar los resultados
  
- Cuando implementamos la estimación de un LATE

  - Incluir los resultados de la primera etapa
  - Discutir la maginitud del estadístico $F$ y la posibilidad de instrumentos débiles
  
- Evitar las tablas de longitud kilométrica

- Siempre describir las tablas dentro del texto (hay pocas cosas más tristes que una tabla huérfana en medio del texto)


---

# Cuando hacemos figuras

- Anotar todas la información relevante para que la figura pueda interpretarse sin leer el texto

  - Incluir etiquetas para los ejes
  
  - Incluir etiquetas para los *breaks* en los ejes que sean claras
  
  - Incluir notas sobre las fuentes de los datos
  
- Usar pocos colores o, de preferencia, escalas de grises

- Quizás la otra cosa tan triste como las tablas huérfanas son las figuras huérfanas: comentar sobre las figuras dentro del texto


---

# Próxima sesión

- Jueves:

  - McKenzie, D. (2012). Beyond baseline and follow-up: The case for more T in experiments. *Journal of development Economics*, 99(2), 210-221.
  - Rojas Valdes, R.I., Wydick, B., & Lybbert, T.J. (2020). Can Hope Elevate Microfinance? Evidence from Oaxaca, Mexico. Forthcoming in *Oxford Economic Papers*.
  
- Martes:

  - MHE, Capítulo 8
  - Ho, D. E., & Imai, K. (2006). Randomization inference with natural experiments: An analysis of ballot effects in the 2003 California recall election. *Journal of the American Statistical Association*, 101(475), 888-900.


---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**


