---
title: "Aplicaciones de diferencia en diferencias"
author: "Irvin Rojas"
institute: "CIDE"
date: "1 de octubre"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")

library(tidyverse)
library(pacman)
library(janitor)
library(sandwich)
#library(nnet)
#library(mlogit)
library(readr)
library(clubSandwich)
library(modelsummary)
library(estimatr)
library(lubridate)
library(ExPanDaR) #for describing panel data
library(lfe)

p_load(tidyverse, foreign, reshape2, psych, qwraps2, forcats, readxl, 
       broom, lmtest, margins, plm, rdrobust, multiwayvcov,
       wesanderson, sandwich, stargazer,
       readstata13, pscore, optmatch, kdensity, MatchIt, bootstrap, matlib, dplyr)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{css, echo = FALSE}
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}
```

.title[
# Sesión 14. Aplicaciones de diferencia en diferencias
]
.subtitle[
## Evaluación de Programas Sociales
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---

class: inverse, middle, center

# Salarios mínimos

---

# Salarios mínimos

- Campos, R. M., Esquivel, G., & Santillán, A. S. (2017). El impacto del salario mínimo en los ingresos y el empleo en México. *Revista CEPAL*.  

- Se explota la homologación en las zonas de salario mínimo en México en el 2013

- La zona B se homlogó a la zona A y, por tanto, tuvo un salto hacia arriba en el salario mínimo

- Podemos comparar antes y después a la zona B contra el resto de las zonas

---

# Salarios mínimos

- Se encuentran efectos positivos en el salario por hora, pero ningún efecto en el empleo

- Usando datos en panel permite incluir las características individuales

- En este ejemplo podemos usar la especificación canónica de un modelo de DID

---

class: inverse, middle, center

# Obesidad y transferencias condicionadas

---

# Obesidad y transferencias condicionadas

- Levasseur, P. (2019). Can social programs break the vicious cycle between poverty and obesity? Evidence from urban Mexico. *World Development*, 113, 143-156.  

- Serio problema de obesidad en los sectores más pobres

- Hay un círculo vicioso

  - Las personas más pobres tienen menores oportunidades en el mercado de trabajo
  - Las personas más pobres tienen patrones de consumo menos sano, lo que los hace más proponsos a sufrir obesidad

- Prospera otorgaba beneficios monetarios condicionados a la asistencia escolar y a clínicas de salud

---

# Obesidad y transferencias condicionadas

- Se emplea un modelo de triple diferencias

- Se trata de tomar en cuenta que en el primer periodo de datos ya se había implementado el Prospera

- En este trabajo se introduce el concepto de PSM

  - El PS nos dice cuál es la probabilidad de permanecer en el programa, dadas una serie de características observables

---

class: inverse, middle, center

# Aborto

---

# Aborto

- Gutiérrez Vázquez, E. Y., & Parrado, E. A. (2016). Abortion legalization and childbearing in Mexico. *Studies in family planning*, 47(2), 113-128.

- Legalización en 2007 del aborto en la Ciudad de México

- Problema de altos índices de embarazos no planeados

- La mortalidad ya venía a la baja

- ¿Cuál es el efecto de la legalización en natalidad?

- Se compara a la Ciudad de México con otras áreas metropolitanas

- La variable dependiente es la probabilidad de haber tenido un hijo el año anterior

- Se encuentra un efecto en las mujeres de 20 a 29 años, pero no en las adolescentes

- Puede haber confusión del efecto de la legislación sobre el aborto o sobre la asesoría en métodos anticonceptivos

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**


