---
title: "Combinación de métodos no experimentales"
author: "Irvin Rojas"
institute: "CIDE"
date: "3 de noviembre"
header-includes:
  - \usepackage{tikz}
  - \usepackage{mathbbm}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")

library(tidyverse)
library(pacman)
library(janitor)
library(sandwich)
#library(nnet)
#library(mlogit)
library(readr)
library(clubSandwich)
library(modelsummary)
library(estimatr)
library(lubridate)
library(ExPanDaR) #for describing panel data
library(lfe)
library(modelsummary)
library(estimatr)
#library(Matching)
#library(MatchIt)
#library(Zelig)
library(gtsummary)
library(miceadds)
library(stargazer)
library(Synth)
library(reshape2)

p_load(tidyverse, foreign, reshape2, psych, qwraps2, forcats, readxl, 
       broom, lmtest, margins, plm, rdrobust, multiwayvcov,
       wesanderson, sandwich, stargazer,
       readstata13, pscore, optmatch, kdensity, MatchIt, bootstrap, matlib, dplyr)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{css, echo = FALSE}
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}
```

.title[
# Sesión 24. Combinación de métodos no experimentales
]
.subtitle[
## Evaluación de Programas Sociales
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---

class: inverse, middle, center

# Efectos de largo plazo

---

# Efectos de largo plazo

- Parker, S. W., & Vogl, T. (2018). Do conditional cash transfers improve economic outcomes in the next generation? Evidence from Mexico (No. w24303). National Bureau of Economic Research. 

- Se busca estimar los efectos de largo plazo de Progresa

- Es un diseño cuasiexperimental pues explotan la aleatorización inicial del programa, pero no pueden seguir a los individuos a lo largo del tiempo

- Se explota el porcentaje de la población que estuvo expuesta al programa en la primera expansión del programa

- Con datos del censo de 2010, podemos saber qué exposición al programa tuvieron las personas que estaban en edad escolar cuando funcionaba el programa

---

# Efectos de largo plazo

- Se estima un modelo de diferencia en diferencias

- Se comparan individuos con distintos niveles de intensidad de cobertura del programa en los municipios donde vivían cuando estaban en la escuela

- Se observa un efecto significativo en educación básica y media

- Hay efectos en migración: los individuos tienen más probabilidad de vivir en zonas urbanas

- Efectos más grandes en las mujeres

---

class: inverse, middle, center

# RD geográfica + PSM

---

# RD geográfica + PSM

- Keele, L., Titiunik, R., & Zubizarreta, J. R. (2015). Enhancing a geographic regression discontinuity design through matching to estimate the effect of ballot initiatives on voter turnout. *Journal of the Royal Statistical Society*. Series A (Statistics in Society), 223-239.

- Efecto de tener una consulta o iniciativa en la participación en elecciones

- Podemos hacer PSM al emparejar individuos que viven en el lugar donde hubo consulta con individuos que viven en donde no hubo consulta

  - El problema es que puede haber características no observables que determinan la elección de dónde vivir

- Podemos hacer RD geográfica al comparar individuos de un lado y del otro de los límites

  - El problema es que la gente seguramente se autoselecciona para vivir, por ejemplo, en donde las casas sean más baratas
  
---

# RD geográfica + PSM

- La combinación de los dos métodos permite comparar unidades a ambos lados de la frontera y que tengan características observables iguales

- La inferencia se realiza por inferencia por aleatorización

---

class: inverse, middle, center

# PSM + DID

---

# PSM + DID

+ Parker, S. W., Saenz, J., & Wong, R. (2018). Health insurance and the aging: Evidence from the Seguro Popular program in Mexico. *Demography*, 55(1), 361-386.  

---

# Próxima sesión

- Hablaremos sobre cientificidad y ética

  - Christensen, G., & Miguel, E. (2018). Transparency, reproducibility, and the credibility of economics research. *Journal of Economic Literature*, 56(3), 920-80.
  
  - Lewis, J. (2020). Experimental Design: Ethics, Integrity, and the Scientific Method. *Handbook of Research Ethics and Scientific Integrity*, 459-474

- Propuesta de fecha del examen final:  **9 de diciembre**

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**


