---
title: "Evaluación, diseño y econometría"
author: "Irvin Rojas"
institute: "CIDE"
date: "18 de agosto de 2020"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Sesión 1. Evaluación, diseño y econometría
]
.subtitle[
## Evaluación de Programas Sociales
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda

1. Presentación mía y de ustedes

1. Descripción general del curso

1. El papel de la teoría, el diseño y la econometría

1. ¿Qué utilidad tiene el curso en su formación?

---

# Descripción general del curso

1. Logística del curso

1. Evaluación

1. Tareas

1. Laboratorios

1. Presentaciones

1. Tiempos para horario de oficina

1. Blog

1. Usemos **Microsoft Teams** casi para todo

---

# Modo a distancia

- Trataremos de hacer la experiencia de aprendizaje lo más cercana posible a la experiencia presencial

- Pero no podemos actuar como si nada pasara

--

- Cosas parecidas

  - Búsquenme para platicar en horas de oficina sobre sus dudas
  - Lean antes de clase
  - Tienen que colaborar para la clase
  
--

- Cosas distintas

  - Cámaras encendidas en clase
  - No grabaremos las sesiones
  - Trataré de partir la clase en bloques: teoría, artículos, código, exposiciones, etc.
  - Tienen que colaborar **más** para la clase con algunos de los bloques
  - El blog sustituye al trabajo final que antes implementaban los estudiantes

---

# ¿Se vale probar?

- ¡Sí!

--

- Se vale que estén en el curso el tiempo máximo que las reglas del CIDE permiten para dar de baja cursos e inscribirse en otros

- Les pido la cortesía de enviarme un correo si deciden dar de baja el curso

- Como ven, nuestro plan de exposiciones y del blog dependerá del número de estudiantes que estén inscritos

- Entre más pronto podamos conocer el número final de estudiantes, mejor para todos

---

# Próxima sesión

- GMPRV, Capítulos 1 y 3 como introducción

- Freedman (1991) sobre la importancia del diseño

- MHE, Capítulo 2 nos permite pensar en cómo podemos pensar los problemas causales como si fueran *experimentos*

- A lo largo del curso vamos a profundizar en los diseños experimentales, pero vamos también a ser críticos sobre ellos y a estudiar otros métodos igual de importantes y útiles

- Nos importan más las preguntas y la teoría detrás de ellas, por eso aprenderemos distintos métodos y trataremos de usar el mejor

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**