---
title: "Aplicaciones de métodos experimentales"
author: "Irvin Rojas"
institute: "CIDE"
date: "3 de septiembre"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
library(knitr)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Sesión 6. Aplicaciones de métodos experimentales
]
.subtitle[
## Evaluación de Programas Sociales
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda

1. En esta sesión ustedes contribuirán a hacer las conclusiones principales de los trabajos

1. Veremos algunas aplicaciones distintas

---

class: inverse, middle, center

# RCT

---

# RCT

- Bruhn, M., Karlan, D., & Schoar, A. (2018). The impact of consulting services on small and medium enterprises: Evidence from a randomized trial in Mexico. *Journal of Political Economy*, 126(2), 635-687.

- Se estima el ITT y esto es interesante porque asemeja lo que suceda en la realidad con las políticas públicas

- Los resultados no pueden ser extrapolados a otros contextos

- Probablemente falto explorar el cumplimiento

- Usa datos del IMSS, los cuales tienes menos error

- Sus conclusiones abordan el mediano plazo, lo cual le da robustez a los resultados



---

class: inverse, middle, center

# Estudios de correspondencia

---

# Estudios de correspondencia

- Arceo-Gomez, E. O., & Campos-Vazquez, R. M. (2014). Race and marriage in the labor market: A discrimination correspondence study in a developing country. *American Economic Review*, 104(5), 376-80.

- Puede que haya trabajos donde el físico es más importante el físico

- En este caso no hay un tratamiento propiamente, se aleatorizan las características en los CVs

- Los fenotipos son aleatorios, por lo que diferencias en las tasa de respuesta se pueden atribuir a discriminación a ciertos fenotipos

- La variable dependiente es la tasa de respuesta

- Importantes implicaciones de política: CVs sin foto, hacer énfasis en combatir la ilegalidad de las restricciones para mujeres solteras, sin hijos


---

class: inverse, middle, center

# Experimento

---

# Experimento

- Seira, E., Elizondo, A., & Laguna-Müggenburg, E. (2017). Are information disclosures effective? evidence from the credit card market. *American Economic Journal: Economic Policy*, 9(1), 277-307-.

- La intervención es proveer información
  - TILA: información puramente financiera
  - Non-TILA: información sobre cómo se compara un cliente con personas parecidas

- ¡Hay en realidad 8 tratamientos!
  
- Los autores construyen celdas cruzando variables observables

- Los tratamientos se aleatorizan dentro de cada una de estas celdas

- Prueba de Kolmogorov: $H_0$ es que la distribuciones son iguales (valores p grandes nos indican que no podemos rechazar la $H_0$)

- Pruebas de poder: con nuestra estrategia empírica, ¿qué efectos podríamos capturar si estos realmente existieran?

- Crítica a la validez externa: usar otro banco



---

# Próxima sesión

- Sesión de laboratorio

  - Usaremos R para ejemplificar algunas ideas de lo que hemos visto sobre experimentos

- Hablaré sobre cómo estimar el LATE usando variables instrumentales

  - Angrist, J. D. (2006). Instrumental variables methods in experimental criminological research: what, why and how. *Journal of Experimental Criminology*, 2(1), 23-44.
  
- El próximo jueves tendremos una exposición de variables instrumentales:

  - McIntosh, C., Alegría, T., Ordóñez, G., & Zenteno, R. (2018). The neighborhood impacts of local infrastructure investment: Evidence from urban Mexico. *American Economic Journal: Applied Economics*, 10(3), 263-86.  

- Pequeños cambios en el [calendario](https://github.com/rojasirvin/EPS2020/blob/master/EPS_calendario_otono_2020.pdf)


---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**


